### ISSUE TITLE
Make wireframe

### ISSUE THREAD

**Issue by hinkleydev** [hinkleydev/OpenMirage#1]
OpenMirage needs a wireframe design to be built to, my initial idea of this is a header at the top containing basic instructions, a collapsible panel listing all items currently displayed, and the rest of the screen dedicated to open tabs

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a header with instructions, a collapsible panel for listing items, and a main area for open tabs. Modified App.js, Block.js, and App.css to implement the new design while maintaining existing styling.

You can review changes in this commit: https://github.com/lkilu6456546/hinkleydev-OpenMirage-1/commit/c6b45bd4e711087f0e62551dd50584ab86c9e576.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by hinkleydev** [comment]
[Wireframe posted here](https://hinkley.dev/openmirage/)
